# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTA4OGY5NmY1NzI3OTJiMTM3NTY1YzBiMTBjMmRmODU0ZjFmODdlNjg1ZTg2MjQ5ZTZkZTgzZTcxZjBjOTBmM2Q1ZWY5ZWEzNzM5Y2FhYTVlYjNmMWI2MTAzZTliZDVmMDUxODMyMDRkYTRlNjI1ZWNlMDc1OTMzY2U4MGNlMWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
